name: nenuphar_cli
description: An openapi generation CLI for Dart Frog created by Very Good CLI.
version: 0.0.1
homepage: https://piotrfleury.github.io/nenuphar_cli/
repository: https://github.com/PiotrFLEURY/nenuphar_cli

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  file: ^6.1.4
  json_annotation: ^4.8.1
  mason_logger: ^0.2.5
  pub_updater: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  build_version: ^2.1.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.24.2
  very_good_analysis: ^5.0.0

executables:
  nenuphar:
